### ISSUE TITLE
deployed in Netlify and it is messed up.

### ISSUE THREAD

**Issue by NiccoloSalvini** [themefisher/kross-hugo#10]
I forked you repo and I followed your video, but the site comes as such:

![Screenshot (14)](https://user-images.githubusercontent.com/47143429/71839553-b3b19a00-30bb-11ea-8dcf-24a5a9fc5581.png)

In the meanwhile I have also done a custom of that, my personal website: [here](https://github.com/NiccoloSalvini/mywebsite) and i still have the same problem, can you check if there are some errors

**Comment by nadershakhshir** [comment]
Same here, i thought i missed something or i screwed something while deploying... looking for a solution soon please.

**Comment by NiccoloSalvini** [comment]
@nadershakhshir did you managed to solve it or you still have the issue? I tried the method for one other template, the megha-something and this a actually work. And then I see something in some other previous issues closed related to this and some people actually me aged to deploy it.

**Comment by themefisherDev** [comment]
@NiccoloSalvini you don't need to customise anything. just clone this repository, don't touch the code. I think you could not provide the same base url. or if you provide the same url then you probably missed the `https://` please fork this template again and do it carefully, and also let me know what happens...

**Comment by NiccoloSalvini** [comment]
Issue solved the problem was: you should do all the passages provided by the authors in the (well done) video, but you should also change the base URL in the config.toml file so that it matches the Netlify auto generated url. Then as a second move you should change both 'cos the auto generated are weird.

**Comment by Aarekaz** [comment]
@NiccoloSalvini I am still having this issue, the base URL and the URL of netlify and forestry is all same.

**Comment by NiccoloSalvini** [comment]
try with this couple solutions:
1) verify that the urls are actually the same, that is because  netlify has changes its own site domains, now it is somethin **.app**, before it was something **.com**
2) try to enter dev tools with f12 in your browser and see if the website is fetching the css [see below] 

![image](https://user-images.githubusercontent.com/47143429/79511479-e6f6b400-802e-11ea-8611-238282be8faf.png)

3) If it is fetching the external css, this could be visible by [see below] 

![image](https://user-images.githubusercontent.com/47143429/79511620-32a95d80-802f-11ea-8844-4487a6b4aa08.png)

**Comment by Aarekaz** [comment]
Thank you soo much. It started working. @NiccoloSalvini Now I have a new issue, the preloader is not working (I think I don't know how to add the pre loader) and when I give categories to the images for my portfolio, the images are not being arranged using the category tags. You can check this in the portfolio section

**Comment by NiccoloSalvini** [comment]
Without seeing the repo it is hard to tell, I can still give you some overlooks of what you might be mistaking. Some points:
1. Verify that the preloader file is either an image or a gif or svg, those are the file suggested type by the developers, I didnt try anything different. Sometimes the issues come up from where you place the image, so try to stick to the forked repo file organization, if the preloader image is put in a certain folder, once you want to change it make sure you put it in the same spot and you name it in the same way. 
1. My preloader litteraly comes from a webpage, so that I put in the toml.config file directly the href of the gif. You might check if your favourite preloader is online and actually do the same.
1. for the categories issue I still suggest you to verify that images used are exactly in the same spot and have the same names as the authors initially set. I have never had this issue so this is the best I can do.

**Comment by Aarekaz** [comment]
@NiccoloSalvini I mean how did you link the preloader into forestry, can you send me a screenshot?
Yeah , I have different names, But what to do it the images exceed the no of images added by the author? @themefisherDev

**Comment by NiccoloSalvini** [comment]
I didn't do it in the Forestry, I use Forestry to manage contents and blog stuff, I perosnally do not use it to edit and modify website.
What I did was forking the repo and starting to edit it in the RStudio. I think you can open it in any editor and do the same.

![image](https://user-images.githubusercontent.com/47143429/79641558-93a07500-8198-11ea-9b04-a00a9911d367.png)
