### ISSUE TITLE
.active class for navigation links

### ISSUE THREAD

**Issue by beebox** [themefisher/kross-hugo#11]
I've looked at the theme, Hugo docs and bootstrap docs.  Is there a way to give a navigation links an 'active' class name for the current page?  My goal is to have the navigation link styled when it has .active class to indicate which page you are on.  It seems Hugo has this capability, but your theme looks a little different than the Hugo examples.

I know this can be done in JS, but I'd rather use the Hugo capability if it is already available.

**Comment by themefisherDev** [comment]
Hey @beebox ,

We are glad to say that your request feature is now available. please pull the latest code. Thanks for being with Themefisher.

**Comment by beebox** [comment]
@themefisherDev That's great, thank you!
