### ISSUE TITLE
Is there a way to add the Window Icon?

### ISSUE THREAD

**Issue by NiccoloSalvini** [themefisher/kross-hugo#12]
I was just trying to figure out if there is the possibility to have a window icon next to the site name. I see it is present in the Megha, can you please check?

**Comment by themefisherDev** [comment]
hey @NiccoloSalvini ,

i didn't get it. can you please give me a screenshot or something that i can understand it properly?

**Comment by NiccoloSalvini** [comment]
![image](https://user-images.githubusercontent.com/47143429/72687505-a0acba00-3afe-11ea-836a-b07b677b75be.png)

I would like to change it, is that possible?

**Comment by themefisherDev** [comment]
Yes! Create an icon with `favicon.png` name and then place it on `static/images` folder.  it will automatically added.
