### ISSUE TITLE
Image categorization is not working for new added images in portfolio 

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/kross-hugo#17]
Hey! The image categorization is not working. When I add a new image from forestry and then when I set the categories, the images are not being shuffled from those categories. Can you look into it? 

![image](https://user-images.githubusercontent.com/36888347/79628179-7484f180-815e-11ea-9f8a-a87d4d801204.png)
As you can see I have given the image a category

but it is not being shuffled in the website. 
![image](https://user-images.githubusercontent.com/36888347/79628195-95e5dd80-815e-11ea-8402-bc3669c893ef.png)

![image](https://user-images.githubusercontent.com/36888347/79628201-9f6f4580-815e-11ea-93c7-c93d0f173bb3.png)

**Comment by Somrat37** [comment]
Hey, I fixed this issue and improve forestry settings, please take a pull.

**Comment by Aarekaz** [comment]
@Somrat37  You mean make a pull request? Its says it cant be megered. Sorry I am a bit new to some of these stuff on GitHub.

**Comment by Somrat37** [comment]
Nope, just download the theme again. it has no more issue and improved forestry settings.

**Comment by Aarekaz** [comment]
That means I will need to re add my details again in the website? Sorry I am a bit confused

**Comment by Somrat37** [comment]
not really, just download the theme then only replace `layout folder` forestry settings and portfolio.yml file with your existing one.

**Comment by Aarekaz** [comment]
So I need to create a new repository?

**Comment by Somrat37** [comment]
No, replace those file with your existing one.

**Comment by Aarekaz** [comment]
I am having trouble understanding. Any way you can do this? If I made you a collaborator ?

**Comment by Somrat37** [comment]
Please contact us throw this email address: themefisher@gmail.com

**Comment by Aarekaz** [comment]
I did, No one replyed.

**Comment by Somrat37** [comment]
please be patient, our team leader will reply to you soon.

**Comment by Aarekaz** [comment]
Will do. Waiting. How do I Meger this lastest commit from you to my repository in my github?

**Comment by Aarekaz** [comment]
@Somrat37  when I upload a image for my portfolio , do I need to upload it into the portfolio media folder?

**Comment by Somrat37** [comment]
you can upload it anywhere in this static folder, but you need to declare the right path on your portfolio.yml file

**Comment by Aarekaz** [comment]
I did, and I replaced the files as you said but the categories are still not showing up . 
![image](https://user-images.githubusercontent.com/36888347/79829012-c11c3700-83c1-11ea-824f-ee4e3ad1ba0f.png)

![image](https://user-images.githubusercontent.com/36888347/79829025-c8434500-83c1-11ea-8e68-f84fe444ca7f.png)
