### ISSUE TITLE
Image categorization is not working

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/kross-hugo#18]
![image](https://user-images.githubusercontent.com/36888347/79947480-be891280-8491-11ea-9d23-2d3a340acf03.png)
![image](https://user-images.githubusercontent.com/36888347/79947475-bd57e580-8491-11ea-8b8c-79f04ebc0805.png)
As you can see even though the categories of the image have been defined, but the categories are to being shown in the website

**Comment by Aarekaz** [comment]
And the website sometimes doesnt load

**Comment by Somrat37** [comment]
hey there, I can see that you didn't update the portfolio.yml file. that's why you are fetching this problem. please update the theme completely, you can download this template and try it on your localhost to see that it is working.

**Comment by Aarekaz** [comment]
@Somrat37 I did, i downloaded the files you said, and replaced it with my files. I think I missed something, let me check again and get back to you
