### ISSUE TITLE
Comments on Blog  and sending form data into netlify forms

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/kross-hugo#20]
Any way we can add comments on the blog page? Is there any way this is possible?

And what should I add here do that the form data goes to [Netlify Forms](https://docs.netlify.com/forms/setup/)  ?

![image](https://user-images.githubusercontent.com/36888347/80563285-59419e00-8a0a-11ea-8e88-80f9993aefaf.png)

**Comment by mehedi-sharif** [comment]
You can use https://disqus.com/ for comments .

Mehedi Sharif
Themefisher
Themefisher@gmail.com
www.themefisher.com

**Comment by Aarekaz** [comment]
I dont see Hugo listed in supported sites

**Comment by Aarekaz** [comment]
@mehedi-sharif Where do I Add the codes mentioned in disqus? I dont want to mess up the code

**Comment by mehedi-sharif** [comment]
We do not have support for Disqus , you have to add yourself or you can hire us to do this job . For more please connect with me personally with my email (mehedi@themefisher.com )
Thanks

Mehedi Sharif
Themefisher
Themefisher@gmail.com
www.themefisher.com

**Comment by Aarekaz** [comment]
@mehedi-sharif  What about form actions? What can I  Put in form action?

**Comment by Somrat37** [comment]
you can add netlify form by editing `content/list.html` file.

**Comment by Aarekaz** [comment]
Do I edit the code?

**Comment by Somrat37** [comment]
yes, you need to edit the form to active netlify form.

**Comment by Somrat37** [comment]
I am going to close this issue, if you have more problems, then create a new issue. thanks
