### ISSUE TITLE
Cannot change the tittle bar icon

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/kross-hugo#21]
How do we change the title bar Icon?
![image](https://user-images.githubusercontent.com/36888347/80669047-2ad3c980-8ac3-11ea-8b22-886f2146cad8.png)

**Comment by Somrat37** [comment]
hey, just place an icon in static/images folder. icon name should be `favicon.png` and size 96*96 px.

**Comment by Aarekaz** [comment]
Yeah, I did that, but It did not change. If you want to check my repo its [here](https://github.com/Praks-Bista/my-site)

**Comment by Aarekaz** [comment]
@Somrat37 Its still now showing up

**Comment by Somrat37** [comment]
Hey, I just check your live URL. and it showing. try to clear your browser cache.

**Comment by Aarekaz** [comment]
@Somrat37 Which Live url? I have not placed my live URL anywhere. the live url is [This](https://prakritibista.com.np/) and its not showing up

**Comment by Aarekaz** [comment]
Thank you It worked.
