### ISSUE TITLE
Disabling the ALL section in porfolio

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/kross-hugo#22]
How can I disable all section in the portfolio page? the page is taking too much time to load so

**Comment by Somrat37** [comment]
You want to disable the hole portfolio page or just the other section except for the portfolio section?

**Comment by Aarekaz** [comment]
No no , I mean I want to remove the ALL category in poerfolio page 
![image](https://user-images.githubusercontent.com/36888347/81462972-dcff4580-91d5-11ea-9e8d-a242ceb66fdc.png)

The ALL category. I want only the Other category to appear.

**Comment by Somrat37** [comment]
hey, then you need to customize the layout of portfolio page. and remove this 3 line of code.
https://github.com/themefisher/kross-hugo/blob/e089b2bb44abdbff00a7dcc1c0f7014f5b88d771/layouts/portfolio/list.html#L11-L13

**Comment by Aarekaz** [comment]
So I just remove those 3 line of code right?

**Comment by Somrat37** [comment]
yes

**Comment by Somrat37** [comment]
did you solve it? now i am going to close this issue, if you face any problem don't hesitate to reopen it, thanks
