### ISSUE TITLE
Problems with deployment on github

### ISSUE THREAD

**Issue by Hyperion101010** [themefisher/kross-hugo#24]
Hi there @somrat-gyver first of all kudos, your theme is the best! really loved developing on it.
I made changes and wanted to deploy them on github. 
As i see i created a docs folder under master and hosted it on github.
To create the static files i just changes the hugo server --themesDir=../.. to hugo themesDir=../.. along with adding publishDir as docs. 

You can take a look at the deployed page (https://hyperion101010.github.io/sbalikondwar/) the repo 
(https://github.com/Hyperion101010/sbalikondwar)
 and I will paste some screenshots here of what it should have looked like.

Please help me, and again keep up the good work.

**Comment by Hyperion101010** [comment]
The expected behaviour:
![Screenshot from 2020-05-29 00-02-03](https://user-images.githubusercontent.com/32175777/83179485-bdf23480-a13f-11ea-853f-eba290995329.png)
![Screenshot from 2020-05-29 00-02-10](https://user-images.githubusercontent.com/32175777/83179490-bf236180-a13f-11ea-963f-c523965af4a5.png)
![Screenshot from 2020-05-29 00-02-16](https://user-images.githubusercontent.com/32175777/83179494-c0548e80-a13f-11ea-9277-500990b4129c.png)

**Comment by somrat-gyver** [comment]
@Hyperion101010 

I can see that you mismatched the baseURL, use this URL https://hyperion101010.github.io/sbalikondwar/ as baseURL in your config.toml file.

**Comment by Hyperion101010** [comment]
thanks it worked like a charm, anyway we can publish this for other developers to refer/use?
Most of the heavy lifting was handled by your effort but i gave it a developer touch :) .

**Comment by mehedi-sharif** [comment]
We are not clear what you actually want to say @Hyperion101010

**Comment by Hyperion101010** [comment]
I just wanted to add my changes as a sample use of the template.

**Comment by somrat-gyver** [comment]
You can add your changes on your repository. thanks for being with themefisher.
