### ISSUE TITLE
Insecure mixed content detected

### ISSUE THREAD

**Issue by Esterng93** [themefisher/kross-hugo#26]
When I follow the steps to set up the page using Netlify and forestry, ultimately I keep getting this error (Insecure mixed content detected) in many of the files and makes the website crash.

**Comment by somrat-gyver** [comment]
hey there, I just check the template in forestry. but I didn't see any kind of error. can you give me a screenshot or screen record?

**Comment by developer-evan** [comment]
I am going to close this issue, if you feel something is not right, then reopen this issue or create a new one. thanks.
