### ISSUE TITLE
How to set image as hero background

### ISSUE THREAD

**Issue by stephenajulu** [themefisher/kross-hugo#28]
Hi, how are you?
I would like to set my image as the hero's background image, could you kindly help me.

**Comment by developer-evan** [comment]
open `index.html` in a test editor, then find the section `hero-area`. remove `bg-primary` class from this section and add `bg-cover` class. then add `style` attribute with bg-image. example `style="background-image : url(images/bg-image.jpg)`

**Comment by stephenajulu** [comment]
Thank you.
