### ISSUE TITLE
Update jQuery and Bootstrap scripts containing XSS vulnerabilities

### ISSUE THREAD

**Issue by christian-bromann** [themefisher/kross-hugo#29]
Let's update these dependencies as they contain XSS vulnerabilities:

- https://snyk.io/vuln/npm:jquery?lh=3.3.1
- https://snyk.io/vuln/npm:bootstrap?lh=4.1.1

**Comment by somratpro** [comment]
we will update it ASAP.

**Comment by developer-evan** [comment]
Hey there, we update the bootstrap and jquery plugins. You can download the latest code from here. 

Also, we would like to ask you for a star to the repository if you didn't already. thanks for being with themefisher.
