### ISSUE TITLE
Compound filter based on tags and categories

### ISSUE THREAD

**Issue by grayknight2** [themefisher/kross-hugo#30]
First of all I have to say that the template is awesome. Congratulations!

I'm trying to make a compound filter in the portfolio page, similar to the one in the following example:
https://vestride.github.io/Shuffle/compound-filters

The colors would be the page categories and the shape the tags, so the only thing I want to add is a check box containing my tags with all options checked by default to re-filter the categories, but I can't handle to modify the JS code by myself.

Any ideas?

**Comment by developer-evan** [comment]
Hey there, I think it's possible, but it needs some hard work. we are available for hiring. you can contact us for any kind of customization at mehedi@themefisher.com [paid].

**Comment by developer-evan** [comment]
Hey @grayknight2 

I am going to close this issue, if you have any more queries feel free to reopen this or create a new one. thanks
