### ISSUE TITLE
Custom logo

### ISSUE THREAD

**Issue by Face2020** [themefisher/kross-hugo#32]
How do you put a custom logo in the upper left corner?
If I remove the .png logo I am getting mistakes in the layout on ipfs.(instead of the website I am getting the maps with files)

**Comment by developer-evan** [comment]
Hey @Face2020 

Please follow this doc to change the logo https://docs.gethugothemes.com/guide/#default-parameters

**Comment by Face2020** [comment]
Thanks I will try.

Op za 24 okt. 2020 06:04 schreef Evan <notifications@github.com>:
