### ISSUE TITLE
Meta Title is the same on all pages

### ISSUE THREAD

**Issue by deepakness** [themefisher/kross-hugo#36]
I set up a Kross theme site ([https://salinipillai.com/](https://salinipillai.com/)) directly from Forestry.io, everything works perfectly fine except all the pages have the same Meta Title.

Whether it's the homepage, about, or blog page; all have the same Title tag which is bad for the SEO.

Any help to resolve would be highly appreciated.

Github repo: [https://github.com/deepakness/salini-hugo](https://github.com/deepakness/salini-hugo)

Thank you.

**Comment by somratpro** [comment]
Hey @deepakness 

I see no issue like this in the demo and my localhost also. Did you change anything?

**Comment by deepakness** [comment]
Thanks for your response, @somratpro

No, I haven't changed anything. I just set up directly from Forestry.io.

Can you please let me know what will I have to do to resolve this?

Thank you.

**Comment by somratpro** [comment]
Hello @deepakness 

I don't see any problem here, so I can suggest that you should clone the repo and give your content in the exampleSite folder. and check that it's working or not. thank you
