### ISSUE TITLE
Numbers/Bullet Points in Markdown Content

### ISSUE THREAD

**Issue by thevirtuoso1973** [themefisher/kross-hugo#37]
This is a feature request to add bullet points and more importantly numbers to generated markdown content.

For example: 
1. blah
2. blah blah
3. blah blah blah

if this above markdown is used in the site, the numbers themselves are not displayed, instead appearing as indented content.

I may be willing to submit a PR if you could point me to where this change could be made, I am a bit of a novice when it comes to customizing hugo layouts/formatting.

**Comment by thevirtuoso1973** [comment]
Ok this change can be made by modifying the `style.css` file in assets/css. 
However, it appears the bullet points/numbers were intentionally removed, so I suppose you may close this issue if you prefer the current design as it is.

**Comment by somratpro** [comment]
@thevirtuoso1973 thank you.
