### ISSUE TITLE
the config file is same with netlify and forestry but the problem still exist

### ISSUE THREAD

**Issue by joshuaogame** [themefisher/kross-hugo#39]
https://dakstest1.netlify.app/

**Comment by somratpro** [comment]
Hello @joshuaogame 

Can you please explain what type of problem you are facing? thank you

**Comment by joshuaogame** [comment]
I placed my icon inside static/images and named it "favicon.png". It shows in my homepage but the tabicon is still the default "K". @somratpro

**Comment by joshuaogame** [comment]
I tried on Microsoft edge browser and weirdly it works. I guess its my google chrome browser. Thanks anyway! you can close this now
