### ISSUE TITLE
Editing footer.html

### ISSUE THREAD

**Issue by keithhardisty** [themefisher/kross-hugo#42]
Hello, I used the one-click forestry.io, netlify, and git install of this theme. I am trying to edit the footer.html (\keithhardisty\themes\kross-hugo\layouts\partials\footer.html) file via the git desktop editor and when I save the changes to the file in my text editor, and then in git desktop, try to "commit  to master", I see an error, as shown below. 

![2021-07-17_16-23-16](https://user-images.githubusercontent.com/71708604/126049659-92c06569-e626-490d-9393-dbcde1f5d763.png)

Any recommendations on what I may be doing wrong. Just want to make some simple tweaks to the theme defaults.

Thank you!

**Comment by tfsomrat** [comment]
hello @keithhardisty 

you need to add those files to the git, follow this instruction.

```
git add --all
git commit -am "commit message"
git push origin master
```
