### ISSUE TITLE
CSS on live site is different from local build, site also loads slow

### ISSUE THREAD

**Issue by LadySith** [themefisher/kross-hugo#8]
I managed to deploy my site on Netlify but on top of it not looking like the local build (the CSS is slightly different, most notably the background color), the site load time is also painfully slow.

Deployed site: [https://www.prosearium.net](https://www.prosearium.net)
Link to source code: [https://github.com/LadySith/prosearium](https://github.com/LadySith/prosearium)

Local build looks like this

![screenshot](https://user-images.githubusercontent.com/9806760/70509787-bb6f3480-1b37-11ea-9214-d13d5788ed6d.PNG)

Live site looks like this

![livesite](https://user-images.githubusercontent.com/9806760/70509981-cb871400-1b37-11ea-9676-c1c630155b73.PNG)

I checked all the gotchas and also looked up other similar problems on the site but haven’t been able to find a solution.

When I posted this on the Hugo forum they recommended I refer this to the theme creator.

Really the most important thing is that I want the background to look just like my local build and I would like the site to load at a decent speed.

Any help would be greatly appreciated.

**Comment by 3manuek** [comment]
Hi @LadySith ! It looks like you changed the theme CSS locally, but the content points to the git repository that your forked at https://github.com/LadySith/kross-hugo-portfolio-template/tree/master/assets/css (which it does not has this update). 

You can manage this through `git submodules`, but mainly you need to push your local changes to the theme fork you created.

**Comment by LadySith** [comment]
Hi @3manuek. Thanks so much for the response.

I pushed the changes to the forked theme and they do show here: https://github.com/LadySith/kross-hugo-portfolio-template/blob/master/assets/css/style.css

But the website isn't reflecting the changes.

I'm not so certain about what I need to do regarding managing the git submodules. I've looked online and I've gone through quite a few convoluted explanation on how git submodules work but I still don't fully understand what exactly I'm trying to do.

Do you have any pointers for this?

**Comment by Somrat37** [comment]
@LadySith , we made an update of this theme, now you can easily change your theme primary color in the config file. and also add some more feature and added forestry cms configuration with video tutorial. hope your problem will be solved. please download the latest code.
